---
language: python
dist: trusty
sudo: required

env:
  - distribution: centos
    version: 7

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --tag=${distribution}-${version}:ansible https://raw.githubusercontent.com/drhelius/travis-ansible-demo/master/travis/Dockerfile.${distribution}-${version}'

install:
  - 'sudo pip install ansible docker'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/selenoid-systemd:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/selenoid-systemd/tests/test.yml --syntax-check'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
