---
language: python
dist: trusty

install:
  - pip install ansible

script:
  - ansible-playbook --syntax-check -i tests/inventory tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
