---
language: python
dist: trusty
sudo: required

install:
  - sudo pip install ansible docker

script:
  - ansible-playbook --syntax-check -i tests/inventory tests/test.yml
  - ansible-playbook -i tests/inventory tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
