---
language: python
dist: trusty
sudo: required

env:
  - distribution: centos
    version: 7

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'git clone --depth=50 --branch=master https://github.com/drhelius/travis-ansible-demo.git travis-ansible-demo/travis'
  - 'sudo docker build --no-cache --rm --file=travis-ansible-demo/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

install:
  - 'sudo pip install ansible docker'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/selenoid-systemd:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/selenoid-systemd/tests/test.yml --syntax-check'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
